insertion_subscribers:
    detections:
        topic: "/yolo/detections_3d"
        template: "DetectionSimple.sparql.tmpl"

# query_time_topic_subscribers:
#     robotBatteryLevel:
#         topic: "/battery_level"
#     robotFootprint:
#         topic: "/polygons"
#     robotTime:
#         topic: "/time"

query_time_tf_subscribers:
    robotPose:
        from_frame: "base_link"
        to_frame: "map"
    gripperPose:
        from_frame: "gripper"
        to_frame: "map"
