all_triples:
    query_file: get_all_triples.sparql

robot_pose:
    query_file: get_robot_pose.sparql

count_triples:
    query_file: count_triples.sparql

person_exists:
    query_file: person_exists.sparql
